/**
 * Load pre-generated niche images and hero videos from data/niche-images.json.
 *
 * Used by archetype layouts to find the right asset URL for each (niche, slot)
 * tuple. If an asset hasn't been generated yet, returns null and the component
 * falls back to a still-image hero or a gradient placeholder.
 *
 * IMPORTANT: We use a static JSON import (NOT fs.readFileSync) so Next.js /
 * Turbopack traces the JSON as a build-time dependency. Without this, when the
 * JSON file changes but no .ts/.tsx source changes, the incremental build
 * cache wrongly thinks the static pages for /examples/[slug] are still valid
 * and serves stale HTML — which means new images / new heroVideo entries
 * never reach the production HTML.
 */

import nicheImagesData from "@/data/niche-images.json";

interface GeneratedImage {
  slot: string;
  url: string;
  width: number;
  height: number;
  prompt: string;
  model: string;
  generated_at: string;
}

interface GeneratedVideo {
  /** Always "hero" for now — service-tile loops are a future phase */
  slot: "hero";
  /** Public CDN URL of the generated video (mp4, hosted by fal) */
  url: string;
  /** Duration in seconds (5 or 10) */
  durationSec: number;
  /** Aspect ratio the video was rendered in */
  aspectRatio?: string;
  prompt: string;
  model: string;
  generated_at: string;
}

interface NicheImageEntry {
  slug: string;
  generated_at: string;
  images: GeneratedImage[];
  /** Optional cinematic hero loop (Seedance 2). When present, the layout uses
   *  it as a `<video>` and falls back to the still hero image as the poster. */
  heroVideo?: GeneratedVideo;
}

interface NicheImagesFile {
  version: number;
  updated_at: string;
  niches: Record<string, NicheImageEntry>;
}

// Cast the imported JSON to our typed shape. The JSON file is generated by
// scripts/qa-generate-images.ts and scripts/qa-generate-videos.ts, both of
// which produce data matching this interface.
const data = nicheImagesData as NicheImagesFile;

/**
 * Get the URL of a specific generated image for a niche + slot.
 * Returns null if not generated yet.
 */
export function getNicheImage(
  nicheSlug: string,
  slot: "hero" | "service1" | "service2" | "service3" | "service4" | "service5" | "service6"
): { url: string; width: number; height: number } | null {
  const niche = data.niches[nicheSlug];
  if (!niche) return null;
  const img = niche.images.find((i) => i.slot === slot);
  if (!img) return null;
  return { url: img.url, width: img.width, height: img.height };
}

/**
 * Return all generated images for a niche in slot order.
 */
export function getNicheImages(nicheSlug: string): GeneratedImage[] {
  return data.niches[nicheSlug]?.images ?? [];
}

/**
 * Get the cinematic hero video for a niche, if one was generated.
 * Returns null if no video — caller should fall back to the still hero image.
 */
export function getNicheHeroVideo(nicheSlug: string): GeneratedVideo | null {
  return data.niches[nicheSlug]?.heroVideo ?? null;
}
